[Environment]::SetEnvironmentVariable('PKR_VAR_client_id', 'REPLACE_ME')
[Environment]::SetEnvironmentVariable('PKR_VAR_client_secret', 'REPLACE_ME')
[Environment]::SetEnvironmentVariable('PKR_VAR_subscription_id', 'REPLACE_ME')
[Environment]::SetEnvironmentVariable('PKR_VAR_tenant_id', 'REPLACE_ME')
[Environment]::SetEnvironmentVariable('PKR_VAR_resource_group_name', 'REPLACE_ME')
[Environment]::SetEnvironmentVariable('PKR_VAR_image_publisher', 'MicrosoftWindowsServer')
[Environment]::SetEnvironmentVariable('PKR_VAR_image_offer', 'WindowsServer')
[Environment]::SetEnvironmentVariable('PKR_VAR_image_sku', '2019-Datacenter')
